# Project: 多核版—大作业
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o loading_and_running_codes.o print_code_and_state.o pick_IN_and_AX.o Transform.o
LINKOBJ  = main.o loading_and_running_codes.o print_code_and_state.o pick_IN_and_AX.o Transform.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = 多核版—大作业.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)

loading_and_running_codes.o: loading_and_running_codes.c
	$(CC) -c loading_and_running_codes.c -o loading_and_running_codes.o $(CFLAGS)

print_code_and_state.o: print_code_and_state.c
	$(CC) -c print_code_and_state.c -o print_code_and_state.o $(CFLAGS)

pick_IN_and_AX.o: pick_IN_and_AX.c
	$(CC) -c pick_IN_and_AX.c -o pick_IN_and_AX.o $(CFLAGS)

Transform.o: Transform.c
	$(CC) -c Transform.c -o Transform.o $(CFLAGS)
